name: wintoast_ffi
description: FFI counterpart of wintoasts.dart.
version: 1.0.0
homepage: https://github.com/alexmercerind/wintoast.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  ffi: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
