name: wintoast
description: A plugin to show native toasts on Windows.
version: 0.0.1
homepage: https://github.com/alexmercerind/wintoast.dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0
  ffi: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WintoastPlugin
